@startuml

	title Initial relationships

	state A
	state B
	state C
	state D
	state E
	state F
	state G
	state H
	state J
	state K
	state L
	state M
	state N
	state O
	state P
	state Q

	A -right-> B
	A -down-> G
	A -down-> E

	B -right-> F
	B -down-> C
	
	C --> B
	C -down-> D
	
	D -down-> H
	D -down-> K

	N -up-> J
	P --> N
	Q --> P
	Q --> O

	K -left-> J
	K -down-> M


	E --> F


	F --> B
	F --> E

	G --> A
	G --> F
	G -right-> C
	G -left-> H

	H --> G
	H -up-> H

	H -left-> L : 1 .. *

 legend
 |Relationships |
|A --> B|
|A --> G|
|A --> E|
|B --> F|
|B --> C|
|-------|
|C --> B|
|C --> D|
|-------|
|D --> H|
|-------|
|E --> F|
|-------|
|F --> B|
|F --> E|
|-------|
|G --> A|
|G --> F|
|G --> C|
|G --> H|
|-------|
|H --> G|
 endlegend	
@enduml
